version: "3"

services:
  mongodb:
    image: andresvidal/rpi3-mongodb3
    volumes:
      - /data/db:/data/db
      - /data/configdb:/data/configdb
    ports:
      - 27017:27017
      - 28017:28017
  homeweather-core:
    build: ./core/
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
    privileged: true
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - mongodb
  homeweather-ui:
    build: ./ui
    environment:
      NODE_ENV: stage
    ports:
      - 8888:80
