# DEPRECATED USE NORMAL DOCKERFILE
FROM resin/rpi-raspbian:latest


RUN apt-get update

RUN apt-get -y install curl gnupg \
    && curl -sL https://deb.nodesource.com/setup_10.x  | bash - \
    && apt-get -y install gcc g++ make nodejs build-essential

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 3000 3001
CMD [ "npm", "start" ]